config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence:true
  validates :address, presence: true
  validates :category, inclusion:{in: ["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence:true, allow_blank:false
  validates :rating, presence:true, allow_blank:false, :numericality => {:only_integer => true}, inclusion:{in: (0..5).to_a}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    set_restaurant
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end


  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>

<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to restaurants_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add Restaurant"), new_restaurant_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.submit %>
  <%= link_to "Index", restaurants_path %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
<h3><%= restaurant.name %></h3>
<p><%= restaurant.address %></p>
<p><%= restaurant.category %></p>
<p><%= restaurant.phone_number %></p>
<%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>
<% @restaurant.reviews.each do |review| %>
<p><%= "*" * review.rating %></p>
<p><%= review.content %></p>
<% end %>

<%= simple_form_for [@restaurant, @review] do |f| %>
<h3><%= @restaurant.name %></h3>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <h3><%= @restaurant.name %></h3>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
  <%= link_to "Back", restaurant_path(@restaurant), class: "btn btn-danger"%>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>